export const currencies = {
"USD":"United States Dollar",
"EUR":"Euro",
"INR":"Indian Rupee",
"AED":"United Arab Emirates Dirham",
"ARS":"Argentine Peso",
"AUD":"Australian Dollar",
"BRL":"Brazilian Real",
"CAD":"Canadian Dollar",
"CHF":"Swiss Franc",
"CLP":"Chilean Peso",
"COP":"Colombian Peso",
"DKK":"Danish Krone",
"EGP":"Egyptian Pound",
"GBP":"Pound Sterling",
"HKD":"Hongkong Dollar",
"IDR":"Indonesian Rupiah",
"ILS":"Israeli New Shekel",
"JPY":"Japanese Yen",
"KRW":"",
"MXN":"",
"MYR":"Malaysian Ringgit",
"NOK":"",
"NZD":"",
"PEN":"",
"PHP":"",
"PLN":"",
"RUB":"",
"SAR":"Saudi Riyal",
"SEK":"Swedish Krona",
"SGD":"Singapore Dollar",
"THB":"Thai Baht",
"TRY":"Turkish lira",
"TWD":"Taiwan Dollar",
"VND":"Vietnamese dong",
"ZAR":"South African Rand",
}